from __future__ import annotations

import argparse

from .commands import (
    command_api, command_completion, command_concept_create_from_evidence, command_concept_list,
    command_concept_officialize, command_concept_show, command_config, command_context, command_db,
    command_doctor, command_env_init, command_eval_create, command_eval_results, command_eval_run,
    command_eval_summary, command_evidence_conflict, command_evidence_queue, command_evidence_reject,
    command_evidence_review, command_evidence_show, command_live, command_local, command_proof_run,
    command_review_preview, command_review_queue,
    command_setup, command_source_jobs, command_source_list, command_source_objects, command_source_show,
    command_source_sync, command_stack, command_status, command_version, command_worker,
)
from .models import DEFAULT_BASE_URL, DEFAULT_TIMEOUT


def add_common_api_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--base-url", default=None, help=f"API base URL. Defaults to CLI config baseUrl or {DEFAULT_BASE_URL}.")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cornerstone",
        description="Cornerstone backend CLI for local setup, live proof, and pilot operations.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    version = subparsers.add_parser("version", help="Print backend package version.")
    version.set_defaults(func=command_version)

    doctor = subparsers.add_parser("doctor", help="Check local cross-platform dev prerequisites.")
    doctor.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    doctor.add_argument("--fix", action="store_true", help="Apply safe local fixes: create .env, reports directory, and chmod scripts on Unix.")
    doctor.add_argument("--dry-run", action="store_true", help="Show fixes without writing files.")
    doctor.set_defaults(func=command_doctor)

    setup = subparsers.add_parser("setup", help="Cross-platform local setup planner and safe fixer.")
    setup.add_argument("target", nargs="?", default="auto", choices=["auto", "local", "macos", "linux", "windows"], help="Target OS profile. Defaults to auto-detected local OS.")
    setup.add_argument("--fix", action="store_true", help="Apply safe local fixes.")
    setup.add_argument("--start-stack", action="store_true", help="Start local PostgreSQL with Docker Compose.")
    setup.add_argument("--migrate", action="store_true", help="Run alembic upgrade head after setup.")
    setup.add_argument("--dry-run", action="store_true")
    setup.add_argument("--json", action="store_true")
    setup.set_defaults(func=command_setup)

    local = subparsers.add_parser("local", help="Local environment lifecycle helpers.")
    local_sub = local.add_subparsers(dest="action", required=True)
    local_reset = local_sub.add_parser("reset", help="Destructively reset the local Docker database volume.")
    local_reset.add_argument("--yes", action="store_true", help="Required confirmation for destructive reset.")
    local_reset.add_argument("--start-after", action="store_true", help="Restart PostgreSQL after reset.")
    local_reset.add_argument("--migrate", action="store_true", help="Run migrations after reset/start.")
    local_reset.add_argument("--dry-run", action="store_true")
    local_reset.set_defaults(func=command_local)

    env = subparsers.add_parser("env", help="Environment helpers.")
    env_sub = env.add_subparsers(dest="action", required=True)
    env_init = env_sub.add_parser("init", help="Create local .env from .env.example.")
    env_init.add_argument("--force", action="store_true", help="Overwrite existing .env.")
    env_init.set_defaults(func=command_env_init)

    stack = subparsers.add_parser("stack", help="Local Docker Compose stack helpers.")
    stack.add_argument("action", choices=["up", "down"])
    stack.add_argument("--migrate", action="store_true", help="Run alembic upgrade head after stack up.")
    stack.add_argument("--dry-run", action="store_true")
    stack.set_defaults(func=command_stack)

    db = subparsers.add_parser("db", help="Database helpers.")
    db.add_argument("action", choices=["migrate", "check-extensions"])
    db.add_argument("--dry-run", action="store_true")
    db.set_defaults(func=command_db)

    api = subparsers.add_parser("api", help="Run the FastAPI development server.")
    api.add_argument("--host", default="127.0.0.1")
    api.add_argument("--port", type=int, default=8000)
    api.add_argument("--reload", action="store_true")
    api.add_argument("--dry-run", action="store_true")
    api.set_defaults(func=command_api)

    worker = subparsers.add_parser("worker", help="Run the sync worker helper.")
    worker.add_argument("--once", action="store_true")
    worker.add_argument("--run-scheduler", action="store_true")
    worker.add_argument("--max-jobs", type=int)
    worker.add_argument("--iterations", type=int)
    worker.add_argument("--sleep-seconds", type=float)
    worker.add_argument("--dry-run", action="store_true")
    worker.set_defaults(func=command_worker)

    live = subparsers.add_parser("live", help="Run gated live proof helpers.")
    live.add_argument("target", choices=["postgres", "notion", "google-drive"])
    live.add_argument("--min-passed", type=int, default=5)
    live.add_argument("--dry-run", action="store_true")
    live.set_defaults(func=command_live)

    status = subparsers.add_parser("status", help="Read /healthz and /v1/sources from a running API.")
    add_common_api_args(status)
    status.set_defaults(func=command_status)

    source = subparsers.add_parser("source", help="Source Studio operations.")
    source_sub = source.add_subparsers(dest="action", required=True)
    source_list = source_sub.add_parser("list", help="List source state.")
    add_common_api_args(source_list)
    source_list.set_defaults(func=command_source_list)
    source_show = source_sub.add_parser("show", help="Show one source.")
    source_show.add_argument("source_id")
    add_common_api_args(source_show)
    source_show.set_defaults(func=command_source_show)
    source_objects = source_sub.add_parser("objects", help="List discovered source objects.")
    source_objects.add_argument("source_id")
    add_common_api_args(source_objects)
    source_objects.set_defaults(func=command_source_objects)
    source_jobs = source_sub.add_parser("jobs", help="List sync jobs for a source.")
    source_jobs.add_argument("source_id")
    add_common_api_args(source_jobs)
    source_jobs.set_defaults(func=command_source_jobs)
    source_sync = source_sub.add_parser("sync", help="Queue a connector sync job for a source.")
    source_sync.add_argument("source_id")
    source_sync.add_argument("--created-by", default="cli")
    source_sync.add_argument("--inline", action="store_true")
    source_sync.add_argument("--max-attempts", type=int, default=3)
    add_common_api_args(source_sync)
    source_sync.set_defaults(func=command_source_sync)

    evidence = subparsers.add_parser("evidence", help="Evidence review workflow.")
    evidence_sub = evidence.add_subparsers(dest="action", required=True)
    evidence_queue = evidence_sub.add_parser("queue", help="List EvidenceFragments needing review.")
    evidence_queue.add_argument("--trust-state", default="unreviewed")
    evidence_queue.add_argument("--source-id")
    evidence_queue.add_argument("--freshness-state")
    evidence_queue.add_argument("--fragment-type")
    evidence_queue.add_argument("--limit", type=int, default=50)
    add_common_api_args(evidence_queue)
    evidence_queue.set_defaults(func=command_evidence_queue)
    evidence_show = evidence_sub.add_parser("show", help="Show one EvidenceFragment.")
    evidence_show.add_argument("evidence_id")
    add_common_api_args(evidence_show)
    evidence_show.set_defaults(func=command_evidence_show)
    for action, func, help_text in [
        ("review", command_evidence_review, "Mark evidence reviewed."),
        ("reject", command_evidence_reject, "Reject evidence."),
        ("conflict", command_evidence_conflict, "Mark evidence conflicted."),
    ]:
        sub = evidence_sub.add_parser(action, help=help_text)
        sub.add_argument("evidence_id")
        sub.add_argument("--reviewer", required=True)
        sub.add_argument("--note")
        add_common_api_args(sub)
        sub.set_defaults(func=func)

    concept = subparsers.add_parser("concept", help="Concept officialization workflow.")
    concept_sub = concept.add_subparsers(dest="action", required=True)
    concept_list = concept_sub.add_parser("list", help="List Concepts.")
    concept_list.add_argument("--status")
    add_common_api_args(concept_list)
    concept_list.set_defaults(func=command_concept_list)
    concept_show = concept_sub.add_parser("show", help="Show one Concept.")
    concept_show.add_argument("concept_id")
    add_common_api_args(concept_show)
    concept_show.set_defaults(func=command_concept_show)
    concept_create = concept_sub.add_parser("create-from-evidence", help="Create Concept candidate from EvidenceFragment.")
    concept_create.add_argument("evidence_id")
    concept_create.add_argument("--name", required=True)
    concept_create.add_argument("--definition", required=True)
    concept_create.add_argument("--body")
    concept_create.add_argument("--owner")
    concept_create.add_argument("--created-by", required=True)
    add_common_api_args(concept_create)
    concept_create.set_defaults(func=command_concept_create_from_evidence)
    concept_officialize = concept_sub.add_parser("officialize", help="Mark Concept official after review.")
    concept_officialize.add_argument("concept_id")
    concept_officialize.add_argument("--reviewer", required=True)
    add_common_api_args(concept_officialize)
    concept_officialize.set_defaults(func=command_concept_officialize)

    review = subparsers.add_parser("review", help="Ontology candidate review operator helpers.")
    review_sub = review.add_subparsers(dest="action", required=True)
    review_queue = review_sub.add_parser("queue", help="Show grouped candidate review queue summary.")
    review_queue.add_argument("--status", default="pending")
    review_queue.add_argument("--run-id")
    review_queue.add_argument("--source-id")
    add_common_api_args(review_queue)
    review_queue.set_defaults(func=command_review_queue)
    review_preview = review_sub.add_parser("preview", help="Preview a candidate approve, merge, or reject action.")
    review_preview.add_argument("candidate_type", choices=["concept", "relation"])
    review_preview.add_argument("candidate_id")
    review_preview.add_argument("--action", default="approve", choices=["approve", "merge", "reject"])
    review_preview.add_argument("--target-id")
    add_common_api_args(review_preview)
    review_preview.set_defaults(func=command_review_preview)

    context = subparsers.add_parser("context", help="Grounded context query helpers.")
    context_sub = context.add_subparsers(dest="action", required=True)
    context_query = context_sub.add_parser("query", help="Call /v1/context/query.")
    context_query.add_argument("query")
    add_common_api_args(context_query)
    context_query.set_defaults(func=command_context)

    ask = subparsers.add_parser("ask", help="Ask a grounded context question.")
    ask.add_argument("query")
    add_common_api_args(ask)
    ask.set_defaults(func=command_context)

    eval_parser = subparsers.add_parser("eval", help="Evaluation helpers.")
    eval_sub = eval_parser.add_subparsers(dest="action", required=True)
    eval_summary = eval_sub.add_parser("summary", help="Call /v1/evaluations/summary.")
    add_common_api_args(eval_summary)
    eval_summary.set_defaults(func=command_eval_summary)
    eval_create = eval_sub.add_parser("create", help="Create an evaluation task.")
    eval_create.add_argument("--name", required=True)
    eval_create.add_argument("--query", required=True)
    eval_create.add_argument("--expected-answer-contains", action="append", default=[])
    eval_create.add_argument("--expected-trust-label")
    eval_create.add_argument("--required-evidence", action="append", default=[])
    eval_create.add_argument("--required-concept", action="append", default=[])
    eval_create.add_argument("--required-decision", action="append", default=[])
    eval_create.add_argument("--require-official-answer", action="store_true")
    eval_create.add_argument("--no-evidence-required", action="store_true")
    eval_create.add_argument("--min-evidence-count", type=int, default=1)
    eval_create.add_argument("--tag", action="append", default=[])
    eval_create.add_argument("--created-by", default="cli")
    add_common_api_args(eval_create)
    eval_create.set_defaults(func=command_eval_create)
    eval_run = eval_sub.add_parser("run", help="Run one evaluation task.")
    eval_run.add_argument("task_id")
    eval_run.add_argument("--evaluated-by", default="cli")
    add_common_api_args(eval_run)
    eval_run.set_defaults(func=command_eval_run)
    eval_results = eval_sub.add_parser("results", help="List evaluation results.")
    eval_results.add_argument("--task-id")
    add_common_api_args(eval_results)
    eval_results.set_defaults(func=command_eval_results)

    proof = subparsers.add_parser("proof", help="Release/pilot proof helpers.")
    proof_sub = proof.add_subparsers(dest="action", required=True)
    proof_run = proof_sub.add_parser("run", help="Run a consolidated release/pilot proof and save a report.")
    proof_run.add_argument("--all", action="store_true", help="Run every proof category. Default when no scope is provided.")
    proof_run.add_argument("--local", action="store_true", help="Run doctor and release-candidate checks.")
    proof_run.add_argument("--local-tests", action="store_true", help="Run ./scripts/run_tests.sh and mypy gate.")
    proof_run.add_argument("--postgres", action="store_true", help="Run live PostgreSQL proof.")
    proof_run.add_argument("--notion", action="store_true", help="Run live Notion E2E proof.")
    proof_run.add_argument("--product-loop", action="store_true", help="Run API product-loop checks against --base-url.")
    proof_run.add_argument("--ontology-loop", action="store_true", help="Run the ontology operator proof checklist against --base-url.")
    proof_run.add_argument("--ssot-readiness", action="store_true", help="Run the v2.0.0 read-only ontology SSOT readiness checklist against --base-url.")
    proof_run.add_argument("--safety-checks", action="store_true", help="Run API safety negative checks against --base-url.")
    proof_run.add_argument("--secret-scan", action="store_true", help="Scan source/docs/reports for Notion token patterns.")
    proof_run.add_argument("--base-url", default=None, help=f"API base URL. Defaults to CLI config baseUrl or {DEFAULT_BASE_URL}.")
    proof_run.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)
    proof_run.add_argument("--query", default="What is Cornerstone?", help="Grounded query used for product-loop proof.")
    proof_run.add_argument("--ontology-focus-concept", default="Settlement", help="Focus Concept for ontology proof and readiness checks.")
    proof_run.add_argument("--reviewer", default="reviewer@example.com", help="Reviewer identity for proof operations that require review.")
    proof_run.add_argument("--confirm-ontology-mutation", action="store_true", help="Required with --ontology-loop because the proof creates explicit proof data and official proof graph objects.")
    proof_run.add_argument("--min-passed", type=int, default=5, help="Minimum live PostgreSQL tests required.")
    proof_run.add_argument("--save", help="Write consolidated JSON report to this path.")
    proof_run.add_argument("--markdown", nargs="?", const="auto", help="Also write a Markdown proof report. Pass a path or omit value for .md beside JSON.")
    proof_run.add_argument("--no-save", action="store_true", help="Do not write a JSON report file.")
    proof_run.add_argument("--continue-on-failure", action="store_true")
    proof_run.add_argument("--dry-run", action="store_true")
    proof_run.add_argument("--json", action="store_true", help="Print machine-readable JSON report.")
    proof_run.set_defaults(func=command_proof_run)


    config = subparsers.add_parser("config", help="Manage CLI profile/config values.")
    config_sub = config.add_subparsers(dest="action", required=True)
    config_get = config_sub.add_parser("get", help="Show CLI config.")
    config_get.add_argument("--json", action="store_true")
    config_get.set_defaults(func=command_config)
    config_set = config_sub.add_parser("set", help="Set CLI config value.")
    config_set.add_argument("key", choices=["baseUrl", "defaultReviewer", "defaultReportsDir"])
    config_set.add_argument("value")
    config_set.set_defaults(func=command_config)
    config_unset = config_sub.add_parser("unset", help="Unset CLI config value.")
    config_unset.add_argument("key", choices=["baseUrl", "defaultReviewer", "defaultReportsDir"])
    config_unset.set_defaults(func=command_config)
    config_path_parser = config_sub.add_parser("path", help="Print CLI config file path.")
    config_path_parser.set_defaults(func=command_config)

    completion = subparsers.add_parser("completion", help="Print shell completion script.")
    completion.add_argument("shell", choices=["bash", "zsh", "powershell"])
    completion.set_defaults(func=command_completion)

    return parser
